import { jsPDF } from "jspdf";
import { INFRABEAT_LOGO, INFRABEAT_LOGO_W, INFRABEAT_LOGO_H } from "./infrabeatLogo.js";

// Builds a polished, multi-page InfraBeat Intelligence Report from the analysis
// blocks. Real selectable text (not screenshots). Each section starts on its
// own page; a two-pass render produces an accurate index with page numbers.

// ── InfraBeat brand palette ──
const IB_RED = [227, 30, 36];     // InfraBeat red
const IB_BLUE = [0, 160, 223];    // InfraBeat blue
const TEAL = [13, 148, 136];
const PURPLE = [124, 58, 237];
const GREEN = [5, 150, 105];
const RED = [220, 38, 38];
const INK = [17, 24, 33];
const SOFT = [90, 100, 115];
const FAINT = [140, 150, 165];
const LINE = [225, 231, 239];

const find = (blocks, type) => blocks.find((b) => b.blockType === type)?.blockData;
const titleOf = (blocks, type, fallback) =>
  blocks.find((b) => b.blockType === type)?.stepTitle || fallback;

export async function generatePDF(blocks, company) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();
  const M = 48;
  let y = M;

  const reportTitle = `InfraBeat Intelligence Report on ${company}`;
  const GENERATOR = "Strategic Intelligence Hub";

  // ── shared layout helpers ──
  // Footer drawn on every body page (cover + index get their own treatment).
  const bodyFooter = () => {
    const pageNum = doc.internal.getCurrentPageInfo().pageNumber;
    doc.setDrawColor(...LINE); doc.setLineWidth(0.5);
    doc.line(M, H - 34, W - M, H - 34);
    doc.setFont("helvetica", "normal"); doc.setFontSize(7.5); doc.setTextColor(...FAINT);
    doc.text(`InfraBeat Intelligence Report · ${company}`, M, H - 22);
    doc.text(`Generated by ${GENERATOR}`, W / 2, H - 22, { align: "center" });
    doc.text(String(pageNum), W - M, H - 22, { align: "right" });
  };

  const need = (h) => {
    if (y + h > H - 48) { doc.addPage(); bodyFooter(); y = M; }
  };

  // A section header that ALSO starts a new page (each section = new page).
  const sectionHeader = (num, title, color) => {
    doc.addPage();
    bodyFooter();
    y = M + 6;
    // number chip
    doc.setFillColor(...color); doc.roundedRect(M, y, 30, 30, 6, 6, "F");
    doc.setFont("helvetica", "bold"); doc.setFontSize(13); doc.setTextColor(255, 255, 255);
    doc.text(String(num).padStart(2, "0"), M + 15, y + 20, { align: "center" });
    // title
    doc.setFont("helvetica", "bold"); doc.setFontSize(17); doc.setTextColor(...INK);
    const tLines = doc.splitTextToSize(title, W - M * 2 - 42);
    doc.text(tLines, M + 42, y + 14);
    y += Math.max(34, tLines.length * 18 + 16);
    // accent underline
    doc.setDrawColor(...color); doc.setLineWidth(2); doc.line(M, y, M + 60, y);
    doc.setLineWidth(0.2);
    y += 18;
    return doc.internal.getCurrentPageInfo().pageNumber; // record page for index
  };

  const para = (text, opts = {}) => {
    const size = opts.size || 10; const color = opts.color || SOFT;
    doc.setFont("helvetica", opts.bold ? "bold" : "normal"); doc.setFontSize(size); doc.setTextColor(...color);
    const lines = doc.splitTextToSize(String(text || ""), opts.width || W - M * 2 - (opts.indent || 0));
    lines.forEach((ln) => { need(size + 4); doc.text(ln, M + (opts.indent || 0), y); y += size + 4; });
  };
  const bullet = (text, color = TEAL) => {
    need(14);
    doc.setFillColor(...color); doc.circle(M + 4, y - 3, 1.5, "F");
    doc.setFont("helvetica", "normal"); doc.setFontSize(10); doc.setTextColor(...SOFT);
    const lines = doc.splitTextToSize(String(text || ""), W - M * 2 - 16);
    lines.forEach((ln) => { need(14); doc.text(ln, M + 14, y); y += 13; });
    y += 2;
  };
  const gap = (h = 10) => { y += h; };

  const pcts = (bullets = []) => {
    const pal = [TEAL, PURPLE, IB_BLUE, GREEN, [180, 130, 30]];
    const out = [];
    bullets.forEach((b, i) => {
      const m = String(b).match(/^(.*?)[\s:—-]*(\d{1,3})\s*%/);
      if (m) out.push({ label: m[1].trim().replace(/[:—-]\s*$/, ""), value: +m[2], color: pal[i % pal.length] });
    });
    return out;
  };
  const drawDonut = (segs, cx, cy, rad) => {
    const total = segs.reduce((s, x) => s + x.value, 0) || 1;
    let a0 = -Math.PI / 2;
    segs.forEach((s) => {
      const a1 = a0 + (s.value / total) * Math.PI * 2;
      const steps = Math.max(2, Math.round((a1 - a0) / 0.12));
      doc.setDrawColor(...s.color); doc.setLineWidth(7);
      for (let i = 0; i < steps; i++) {
        const t0 = a0 + ((a1 - a0) * i) / steps;
        const t1 = a0 + ((a1 - a0) * (i + 1)) / steps;
        doc.line(cx + rad * Math.cos(t0), cy + rad * Math.sin(t0), cx + rad * Math.cos(t1), cy + rad * Math.sin(t1));
      }
      a0 = a1;
    });
    doc.setLineWidth(0.2);
    let ly = cy - rad + 4;
    segs.forEach((s) => {
      doc.setFillColor(...s.color); doc.rect(cx + rad + 16, ly - 6, 7, 7, "F");
      doc.setFont("helvetica", "normal"); doc.setFontSize(9); doc.setTextColor(...SOFT);
      doc.text(`${s.label}`, cx + rad + 28, ly);
      doc.setFont("helvetica", "bold"); doc.setTextColor(...INK);
      doc.text(`${Math.round((s.value / total) * 100)}%`, cx + rad + 150, ly);
      ly += 16;
    });
  };
  const drawSeverity = (high, med, low) => {
    const total = high + med + low || 1;
    const barW = W - M * 2, barH = 8;
    let x = M;
    [[high, RED], [med, [180, 130, 30]], [low, FAINT]].forEach(([n, c]) => {
      const w = (n / total) * barW;
      if (w > 0) { doc.setFillColor(...c); doc.rect(x, y, w, barH, "F"); x += w; }
    });
    y += barH + 12;
    doc.setFont("helvetica", "normal"); doc.setFontSize(8);
    let lx = M;
    [["High", high, RED], ["Medium", med, [180, 130, 30]], ["Low", low, FAINT]].forEach(([lbl, n, c]) => {
      doc.setFillColor(...c); doc.rect(lx, y - 6, 6, 6, "F");
      doc.setTextColor(...SOFT); doc.text(`${lbl} ${n}`, lx + 10, y);
      lx += 70;
    });
    y += 16;
  };

  // ── Build the ordered section list by walking blocks in step order ──
  // Each entry: { title, color, render() }. This drives both the body pass and
  // the index, so numbering and order always match.
  const ordered = [...blocks]
    .filter((b) => b.blockData)
    .sort((a, b) => (a.stepNumber || 0) - (b.stepNumber || 0));

  const palette = [IB_RED, GREEN, TEAL, PURPLE, IB_BLUE, GREEN, TEAL, PURPLE, IB_BLUE, GREEN, PURPLE, RED, GREEN];

  const sections = ordered.map((b, idx) => {
    const color = palette[idx % palette.length];
    const data = b.blockData;
    const title = b.stepTitle || b.blockType;
    return {
      title,
      color,
      render() {
        switch (b.blockType) {
          case "HERO": {
            para(data.key_insight || "", { size: 11, color: INK });
            gap(8);
            if (data.sales_angle) {
              para("VALUE PROPOSITION", { bold: true, size: 9, color: IB_RED });
              para(data.sales_angle, { size: 10 });
            }
            gap(6);
            const meta = [data.industry, data.region, data.growth_stage].filter(Boolean).join("   ·   ");
            if (meta) para(meta, { size: 9, color: FAINT });
            break;
          }
          case "METRICS": {
            (data.items || []).forEach((m) => {
              need(18);
              doc.setFont("helvetica", "bold"); doc.setFontSize(11); doc.setTextColor(...INK);
              doc.text(String(m.value || ""), M, y);
              doc.setFont("helvetica", "normal"); doc.setTextColor(...SOFT); doc.setFontSize(10);
              doc.text(`— ${m.label || ""}`, M + 120, y);
              const sc = m.signal === "positive" ? GREEN : m.signal === "negative" ? RED : FAINT;
              doc.setTextColor(...sc); doc.setFontSize(8);
              doc.text(String(m.signal || "").toUpperCase(), W - M, y, { align: "right" });
              y += 18;
            });
            break;
          }
          case "CARD_GRID": {
            const pctCard = (data.cards || []).find((c) => pcts(c.bullets).length >= 2);
            if (pctCard) {
              const segs = pcts(pctCard.bullets);
              need(110);
              doc.setFont("helvetica", "bold"); doc.setFontSize(9); doc.setTextColor(...color);
              doc.text((pctCard.title || "").toUpperCase(), M, y); y += 8;
              drawDonut(segs, M + 45, y + 42, 38);
              y += 100;
            }
            (data.cards || []).forEach((c) => {
              need(22);
              doc.setFont("helvetica", "bold"); doc.setFontSize(11); doc.setTextColor(...color);
              doc.text(c.title || "", M, y); y += 15;
              (c.bullets || []).forEach((bl) => bullet(bl, color));
              gap(6);
            });
            break;
          }
          case "PAIN_POINTS": {
            const high = (data.points || []).filter((p) => p.severity === "high").length;
            const med = (data.points || []).filter((p) => p.severity === "medium").length;
            const low = (data.points || []).filter((p) => p.severity === "low").length;
            drawSeverity(high, med, low);
            (data.points || []).forEach((p) => {
              need(30);
              const sc = p.severity === "high" ? RED : p.severity === "medium" ? [180, 83, 9] : FAINT;
              doc.setFont("helvetica", "bold"); doc.setFontSize(11); doc.setTextColor(...INK);
              doc.text(p.title || "", M, y);
              doc.setFontSize(8); doc.setTextColor(...sc);
              doc.text((p.severity || "").toUpperCase(), W - M, y, { align: "right" });
              y += 14;
              para(p.description || "", { size: 9, color: SOFT }); gap(6);
            });
            break;
          }
          case "DECISION_MAKERS": {
            const people = data.people || [];
            if (!people.length) {
              para("No public LinkedIn profiles were found for this company's decision-makers. This is common for smaller or privately-held companies whose leadership isn't publicly indexed.", { size: 10, color: SOFT });
              break;
            }
            people.forEach((p) => {
              need(38);
              doc.setFont("helvetica", "bold"); doc.setFontSize(12); doc.setTextColor(...INK);
              doc.text(p.name || "", M, y); y += 14;
              if (p.title) { doc.setFont("helvetica", "normal"); doc.setFontSize(9.5); doc.setTextColor(...SOFT); doc.text(p.title, M, y); y += 13; }
              if (p.url) {
                doc.setFont("helvetica", "normal"); doc.setFontSize(8.5); doc.setTextColor(...IB_BLUE);
                doc.textWithLink(p.url, M, y, { url: p.url }); y += 14;
              }
              gap(6);
            });
            break;
          }
          case "PERSONAS": {
            (data.personas || []).forEach((p) => {
              need(52);
              doc.setFont("helvetica", "bold"); doc.setFontSize(12); doc.setTextColor(...INK);
              doc.text(p.role || "", M, y); y += 15;
              para("Focus: " + (p.focus || ""), { size: 9 });
              para("Motivation: " + (p.motivation || ""), { size: 9 });
              para("Likely objection: \"" + (p.objection || "") + "\"", { size: 9, color: RED });
              gap(8);
            });
            break;
          }
          case "ROADMAP": {
            (data.phases || []).forEach((phase, i) => {
              need(34);
              const c = [IB_RED, IB_BLUE, GREEN][i % 3];
              doc.setFont("helvetica", "bold"); doc.setFontSize(12); doc.setTextColor(...c);
              doc.text(`Phase ${i + 1}: ${phase.phase || ""}`, M, y); y += 16;
              (phase.actions || []).forEach((a) => bullet(a, c));
              gap(8);
            });
            break;
          }
          case "TABLE": {
            const cols = data.columns || [];
            const colW = (W - M * 2) / (cols.length || 1);
            need(20);
            doc.setFont("helvetica", "bold"); doc.setFontSize(8); doc.setTextColor(...color);
            cols.forEach((c, i) => doc.text((c || "").toUpperCase(), M + i * colW, y));
            y += 6; doc.setDrawColor(...LINE); doc.line(M, y, W - M, y); y += 12;
            doc.setFont("helvetica", "normal"); doc.setFontSize(9); doc.setTextColor(...SOFT);
            (data.rows || []).forEach((row) => {
              need(16);
              const cells = row.cells || [];
              let maxLines = 1;
              cells.forEach((cell, i) => {
                const lines = doc.splitTextToSize(String(cell || ""), colW - 6);
                maxLines = Math.max(maxLines, lines.length);
                lines.forEach((ln, li) => doc.text(ln, M + i * colW, y + li * 11));
              });
              y += maxLines * 11 + 6;
              doc.setDrawColor(...LINE); doc.line(M, y - 4, W - M, y - 4);
            });
            break;
          }
          case "INSIGHTS": {
            (data.insights || []).forEach((ins, i) => {
              need(16);
              doc.setFont("helvetica", "bold"); doc.setFontSize(9); doc.setTextColor(...color);
              doc.text(String(i + 1).padStart(2, "0"), M, y);
              doc.setFont("helvetica", "normal"); doc.setTextColor(...SOFT);
              const lines = doc.splitTextToSize(ins, W - M * 2 - 20);
              lines.forEach((ln, li) => { need(13); doc.text(ln, M + 20, y + li * 12); });
              y += lines.length * 12 + 5;
            });
            break;
          }
          case "SOLUTIONS": {
            (data.solutions || []).forEach((s) => {
              need(42);
              doc.setFont("helvetica", "bold"); doc.setFontSize(12); doc.setTextColor(...INK);
              doc.text(s.name || "", M, y); y += 15;
              para("Problem: " + (s.problem_solved || ""), { size: 9, color: SOFT });
              para("Impact: " + (s.impact || ""), { size: 9, color: GREEN, bold: true });
              gap(8);
            });
            break;
          }
          default:
            para(JSON.stringify(data), { size: 8, color: FAINT });
        }
      },
    };
  });

  // ════════════ PASS 1: render the body (sections), recording page numbers ════════════
  // We start on page 1 (the cover placeholder) — but the cover + index are
  // inserted at the very end via insertPage, so body sections render first here
  // and we offset the recorded page numbers by the number of front-matter pages.
  const FRONT_PAGES = 2; // cover + index
  const indexEntries = [];

  sections.forEach((sec, i) => {
    const startedPage = sectionHeader(i + 1, sec.title, sec.color);
    indexEntries.push({ num: i + 1, title: sec.title, page: startedPage });
    sec.render();
  });

  // The first body section called addPage(), creating an extra blank page 1.
  // Remove that leading blank page so the body starts cleanly.
  // (jsPDF starts with 1 page; our first sectionHeader added a 2nd. Delete p1.)
  doc.deletePage(1);

  // Now recorded pages are off by 1 (we removed a page before them) and need to
  // be shifted by FRONT_PAGES (cover+index inserted ahead). Net offset:
  // recorded page P became (P-1) after deletePage(1), then +FRONT_PAGES.
  const pageShift = FRONT_PAGES - 1;
  indexEntries.forEach((e) => { e.page += pageShift; });

  // ════════════ PASS 2: cover + index, inserted at the front ════════════
  // Insert index page first (becomes new page 1), then cover (becomes page 1,
  // pushing index to 2). jsPDF insertPage(n) inserts BEFORE page n.

  // --- INDEX (insert before current page 1) ---
  doc.insertPage(1);
  doc.setPage(1);
  drawIndex();

  // --- COVER (insert before index) ---
  doc.insertPage(1);
  doc.setPage(1);
  drawCover();

  function drawCover() {
    // White background with InfraBeat red accents.
    doc.setFillColor(255, 255, 255); doc.rect(0, 0, W, H, "F");
    // Top red band
    doc.setFillColor(...IB_RED); doc.rect(0, 0, W, 10, "F");
    // Side red rule
    doc.setFillColor(...IB_RED); doc.rect(0, 0, 6, H, "F");

    // Logo (centered upper third)
    const logoW = 200;
    const logoH = logoW * (INFRABEAT_LOGO_H / INFRABEAT_LOGO_W);
    try { doc.addImage(INFRABEAT_LOGO, "PNG", (W - logoW) / 2, 150, logoW, logoH); } catch { /* ignore */ }

    // Eyebrow
    doc.setFont("helvetica", "bold"); doc.setFontSize(10); doc.setTextColor(...IB_RED);
    doc.text("STRATEGIC INTELLIGENCE REPORT", W / 2, 300, { align: "center" });

    // Title: InfraBeat Intelligence Report on [Company]
    doc.setFont("helvetica", "bold"); doc.setFontSize(26); doc.setTextColor(...INK);
    const tl = doc.splitTextToSize(`Intelligence Report on ${company}`, W - M * 3);
    doc.text(tl, W / 2, 350, { align: "center" });

    // Divider
    doc.setDrawColor(...IB_RED); doc.setLineWidth(1.5);
    doc.line(W / 2 - 40, 350 + tl.length * 30 + 6, W / 2 + 40, 350 + tl.length * 30 + 6);
    doc.setLineWidth(0.2);

    // Generated-by + date (bottom)
    doc.setFont("helvetica", "normal"); doc.setFontSize(11); doc.setTextColor(...SOFT);
    doc.text("Generated by Strategic Intelligence Hub", W / 2, H - 120, { align: "center" });
    doc.setFontSize(9); doc.setTextColor(...FAINT);
    doc.text(new Date().toLocaleDateString(undefined, { year: "numeric", month: "long", day: "numeric" }), W / 2, H - 102, { align: "center" });

    // Bottom red band
    doc.setFillColor(...IB_RED); doc.rect(0, H - 10, W, 10, "F");
  }

  function drawIndex() {
    doc.setFillColor(255, 255, 255); doc.rect(0, 0, W, H, "F");
    doc.setFillColor(...IB_RED); doc.rect(0, 0, 6, H, "F");

    let iy = M + 20;
    doc.setFont("helvetica", "bold"); doc.setFontSize(20); doc.setTextColor(...INK);
    doc.text("Contents", M, iy);
    doc.setDrawColor(...IB_RED); doc.setLineWidth(2); doc.line(M, iy + 8, M + 50, iy + 8);
    doc.setLineWidth(0.2);
    iy += 44;

    indexEntries.forEach((e) => {
      if (iy > H - 60) return; // safety; 13 entries fit comfortably
      doc.setFont("helvetica", "bold"); doc.setFontSize(10); doc.setTextColor(...IB_RED);
      doc.text(String(e.num).padStart(2, "0"), M, iy);
      doc.setFont("helvetica", "normal"); doc.setFontSize(11); doc.setTextColor(...INK);
      const tw = doc.getTextWidth(e.title);
      doc.text(e.title, M + 28, iy);
      // dotted leader
      const dotStart = M + 28 + tw + 8;
      const dotEnd = W - M - 24;
      doc.setTextColor(...FAINT); doc.setFontSize(9);
      if (dotEnd > dotStart) {
        const dots = ".".repeat(Math.max(0, Math.floor((dotEnd - dotStart) / 3)));
        doc.text(dots, dotStart, iy, { maxWidth: dotEnd - dotStart });
      }
      // page number
      doc.setFont("helvetica", "bold"); doc.setFontSize(10); doc.setTextColor(...INK);
      doc.text(String(e.page), W - M, iy, { align: "right" });
      iy += 26;
    });

    // index footer
    doc.setFont("helvetica", "normal"); doc.setFontSize(7.5); doc.setTextColor(...FAINT);
    doc.text(`InfraBeat Intelligence Report · ${company}`, M, H - 22);
    doc.text(`Generated by ${GENERATOR}`, W - M, H - 22, { align: "right" });
  }

  doc.save(`InfraBeat_Intelligence_Report_${company.replace(/[^a-z0-9]/gi, "_")}.pdf`);
}
